services:
  db:
    container_name: ${DATABASE_CONTAINER_NAME}
    image: "postgres"
    restart: always
    shm_size: 120mb
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
